
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift
    - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
    - explicit_self
file_length:
    warning: 500
    error: 100
line_length:
    warning: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
